# Generated by Django 3.1.2 on 2020-12-04 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201203_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contacts',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='contacts',
            name='contactsOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='contacts', to='main.messagedocument', verbose_name='Message'),
        ),
    ]
