# Generated by Django 3.1.2 on 2020-12-04 23:11

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201204_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contacts',
            field=picklefield.fields.PickledObjectField(default=1, editable=False),
        ),
    ]
